# Generated by Django 5.0.7 on 2024-08-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0005_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
