# Generated by Django 5.0.7 on 2024-08-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0007_alter_car_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
