# Generated by Django 5.0.7 on 2024-08-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0008_alter_car_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarByCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='cars/')),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
