# Generated by Django 5.0.7 on 2024-08-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0010_carbycompanyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarByCompanyImage',
        ),
    ]
