# Generated by Django 5.0.7 on 2024-08-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0011_delete_carbycompanyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbycompany',
            name='image',
            field=models.ImageField(upload_to='cars_by_company/'),
        ),
        migrations.CreateModel(
            name='CarByCompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_by_company/')),
                ('car_by_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dealership.carbycompany')),
            ],
        ),
    ]
