# Generated by Django 5.0.7 on 2024-08-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0012_alter_carbycompany_image_carbycompanyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_number',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(blank=True, choices=[('honda', 'Honda'), ('toyota', 'Toyota'), ('suzuki', 'Suzuki'), ('nissan', 'Nissan'), ('mercedes', 'Mercedes'), ('bmw', 'Bmw'), ('audi', 'Audi'), ('kia', 'Kia'), ('huyandai', 'Huyandai'), ('changan', 'Changan'), ('haval', 'Haval'), ('mg', 'Mg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carbycompany',
            name='company',
            field=models.CharField(blank=True, choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Suzuki', 'Suzuki'), ('Nissan', 'Nissan'), ('Mercedes', 'Mercedes'), ('Bmw', 'Bmw'), ('Audi', 'Audi'), ('Kia', 'Kia'), ('Huyandai', 'Huyandai'), ('Changan', 'Changan'), ('Haval', 'Haval'), ('Mg', 'Mg')], max_length=100, null=True),
        ),
    ]
