# Generated by Django 5.0.7 on 2024-08-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0013_rename_model_number_car_year_alter_car_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='name',
        ),
    ]
