# Generated by Django 5.0.7 on 2024-08-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0014_rename_model_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
