# Generated by Django 5.0.7 on 2024-08-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0018_alter_carbycompany_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbycompany',
            name='model',
        ),
        migrations.AddField(
            model_name='carbycompany',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
