# Generated by Django 5.0.7 on 2024-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0019_remove_carbycompany_model_carbycompany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbycompany',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='carbycompany',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
