# Generated by Django 5.0.7 on 2024-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0020_carbycompany_color_carbycompany_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
