# Generated by Django 5.0.7 on 2024-08-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0021_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
