# Generated by Django 5.0.7 on 2024-08-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0022_appointment_date_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='checked_status',
            field=models.BooleanField(default=False),
        ),
    ]
