# Generated by Django 5.0.7 on 2024-08-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0023_contact_checked_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_status',
            field=models.BooleanField(default=False),
        ),
    ]
