# Generated by Django 5.0.7 on 2024-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0024_appointment_checked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbycompany',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbycompany',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
