# Generated by Django 5.0.7 on 2024-08-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0025_alter_car_mileage_alter_car_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.carbycompany')),
            ],
        ),
    ]
