# Generated by Django 5.0.7 on 2024-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0026_soldcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cars/videos/'),
        ),
    ]
