# Generated by Django 5.0.7 on 2024-08-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0027_car_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbycompany',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cars_by_company/videos/'),
        ),
    ]
