# Generated by Django 5.0.7 on 2024-09-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0028_carbycompany_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcar',
            name='car_type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Fourdoor', 'Fourdoor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='soldcar',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='soldcar',
            name='company',
            field=models.CharField(blank=True, choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Suzuki', 'Suzuki'), ('Nissan', 'Nissan'), ('Mercedes', 'Mercedes'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('KIA', 'KIA'), ('Huyandai', 'Huyandai'), ('Changan', 'Changan'), ('Haval', 'Haval'), ('MG', 'MG')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soldcar',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='soldcar',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldcar',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldcar',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Fourdoor', 'Fourdoor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(blank=True, choices=[('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Suzuki', 'Suzuki'), ('Nissan', 'Nissan'), ('Mercedes', 'Mercedes'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('KIA', 'KIA'), ('Huyandai', 'Huyandai'), ('Changan', 'Changan'), ('Haval', 'Haval'), ('MG', 'MG')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soldcar',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
