# Generated by Django 5.0.7 on 2024-09-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0029_soldcar_car_type_soldcar_color_soldcar_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcar',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
