# Generated by Django 5.0.7 on 2024-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0030_soldcar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcar',
            name='Profit',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
